import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { mkdtempSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import type { ConnectionProfile, InspectColumn } from '../../src/electron'
import { buildAddConstraint, buildAddForeignKey, buildAddPartition, buildColumnAlter, buildCreateIndex, buildCreateTrigger } from '../../src/sql-write'

const inspectColumnFixture = (name: string): InspectColumn =>
  ({ name, dataType: 'integer', nullable: true, default: null, primaryKey: false, comment: null })
import type { Driver } from './driver'
import { MAX_BUFFERED_ROWS } from './driver'
import { createPostgresDriver } from './postgres'
import { adminPool, endpointFor, profileFromUrl, testDatabaseUrl, testPooledDatabaseUrl } from './test-db'

const url = testDatabaseUrl()
const describeDb = url ? describe : describe.skip

// Exercises the real Postgres driver against TEST_DATABASE_URL. Skips entirely
// when no test database is configured (see .env.example).
describeDb('postgres driver (integration)', () => {
  const dbUrl = url ?? ''
  let admin: ReturnType<typeof adminPool>

  beforeAll(async () => {
    admin = adminPool(dbUrl)
    // A throwaway schema so assertions don't depend on whatever else lives in
    // the database; dropped wholesale afterwards.
    await admin.query('drop schema if exists sqlkit_it cascade')
    await admin.query('create schema sqlkit_it')
    await admin.query('create table sqlkit_it.authors (id serial primary key, name text not null, bio text)')
    await admin.query(
      `create table sqlkit_it.books (
         id serial primary key,
         author_id integer not null references sqlkit_it.authors(id),
         title text not null,
         published boolean default false)`,
    )
    await admin.query('create index books_author_idx on sqlkit_it.books(author_id)')
    await admin.query('create view sqlkit_it.book_titles as select title from sqlkit_it.books')
    await admin.query("create type sqlkit_it.mood as enum ('happy', 'sad')")
    await admin.query("insert into sqlkit_it.authors (name, bio) values ('Ada', 'pioneer'), ('Alan', null)")
  })

  afterAll(async () => {
    await admin.query('drop schema if exists sqlkit_it cascade').catch(() => {})
    await admin.end().catch(() => {})
  })

  const connectDriver = async (overrides: Partial<ConnectionProfile> = {}): Promise<Driver> => {
    const profile = profileFromUrl(dbUrl, overrides)
    const driver = createPostgresDriver(profile, endpointFor(profile), { onError: () => {} })
    await driver.connect()
    return driver
  }

  it('swaps two column names in one runDdl without a transient collision', async () => {
    const driver = await connectDriver()
    try {
      await admin.query('drop table if exists sqlkit_it.swap_probe')
      await admin.query('create table sqlkit_it.swap_probe (a int, b int)')
      await admin.query('insert into sqlkit_it.swap_probe values (1, 2)')
      const statements = buildColumnAlter({ schema: 'sqlkit_it', name: 'swap_probe', kind: 'table' }, [
        { original: inspectColumnFixture('a'), name: 'b' },
        { original: inspectColumnFixture('b'), name: 'a' },
      ], 'postgresql')
      const outcome = await driver.runDdl!(statements)
      expect(outcome.success).toBe(true)
      // Names swapped: column "a" now holds b's old value (2), "b" holds a's (1).
      expect((await driver.query('select a, b from sqlkit_it.swap_probe')).rows).toEqual([[2, 1]])
    } finally {
      await admin.query('drop table if exists sqlkit_it.swap_probe').catch(() => {})
      await driver.disconnect()
    }
  })

  it('flags a generated column in inspectTable', async () => {
    const driver = await connectDriver()
    try {
      await admin.query('drop table if exists sqlkit_it.gen_probe')
      await admin.query(`create table sqlkit_it.gen_probe (
        a int,
        total int generated always as (a + 1) stored,
        identity_always bigint generated always as identity,
        identity_default bigint generated by default as identity)`)
      const inspection = await driver.inspectTable({ schema: 'sqlkit_it', name: 'gen_probe', kind: 'table' })
      const byName = new Map(inspection.columns.map((column) => [column.name, column]))
      expect(byName.get('total')?.generated).toBe(true)
      expect(byName.get('a')?.generated).toBe(false)
      expect(byName.get('identity_always')?.identity).toBe('always')
      expect(byName.get('identity_default')?.identity).toBe('default')
    } finally {
      await admin.query('drop table if exists sqlkit_it.gen_probe').catch(() => {})
      await driver.disconnect()
    }
  })

  const exportFile = (name: string) => join(mkdtempSync(join(tmpdir(), 'sqlkit-pg-export-')), name)

  it('streams a full result to a CSV file via exportQuery', async () => {
    const driver = await connectDriver()
    const file = exportFile('authors.csv')
    try {
      const result = await driver.exportQuery!({
        sql: 'select name from sqlkit_it.authors order by id',
        params: [],
        childDb: null,
        sort: null,
        filePath: file,
        format: 'csv',
      })
      expect(result.rowCount).toBe(2)
      expect(readFileSync(file, 'utf8')).toBe('name\nAda\nAlan\n')
    } finally {
      await driver.disconnect()
    }
  })

  // The point of the sql format: the exported statements must load back into the
  // database unchanged, so the escaping in result-sql is checked against the real
  // server rather than an expected string.
  it('exports INSERT statements that round-trip through the server', async () => {
    const driver = await connectDriver()
    const file = exportFile('rows.sql')
    try {
      await admin.query('drop table if exists sqlkit_it.trip_src, sqlkit_it.trip_dst')
      await admin.query(`create table sqlkit_it.trip_src (
        id bigint, note text, amount numeric(20,4), flag boolean, blob bytea, doc jsonb, missing text)`)
      await admin.query(`insert into sqlkit_it.trip_src values
        (9007199254740993, 'O''Brien said "hi"', 0.10000000000000000001, true, '\\xdead00beef'::bytea, '{"a":[1,2]}', null),
        (-1, e'back\\\\slash and \\nnewline', -12345678901234.5678, false, '\\x'::bytea, '[]', 'x')`)
      await admin.query('create table sqlkit_it.trip_dst (like sqlkit_it.trip_src)')

      const result = await driver.exportQuery!({
        sql: 'select * from sqlkit_it.trip_src order by id',
        params: [],
        childDb: null,
        sort: null,
        filePath: file,
        format: 'sql',
        sqlTarget: { engine: 'postgresql', table: { schema: 'sqlkit_it', name: 'trip_dst', kind: 'table' } },
      })
      expect(result.rowCount).toBe(2)
      await admin.query(readFileSync(file, 'utf8'))
      const diff = await admin.query(`select count(*)::int as n from (
        (select * from sqlkit_it.trip_src except select * from sqlkit_it.trip_dst)
        union all
        (select * from sqlkit_it.trip_dst except select * from sqlkit_it.trip_src)) d`)
      expect(diff.rows[0].n).toBe(0)
    } finally {
      await admin.query('drop table if exists sqlkit_it.trip_src, sqlkit_it.trip_dst').catch(() => {})
      await driver.disconnect()
    }
  })

  it('exports past the in-memory row cap', async () => {
    const driver = await connectDriver()
    const file = exportFile('series.csv')
    const rows = MAX_BUFFERED_ROWS + 10_000
    try {
      const result = await driver.exportQuery!({
        sql: `select g from generate_series(1, ${rows}) g`,
        params: [],
        childDb: null,
        sort: null,
        filePath: file,
        format: 'csv',
      })
      expect(result.rowCount).toBe(rows)
      // Header + every data row, proving the export bypassed the display cap.
      expect(readFileSync(file, 'utf8').trimEnd().split('\n')).toHaveLength(rows + 1)
    } finally {
      await driver.disconnect()
    }
  })

  it('connects and reports the server version', async () => {
    const profile = profileFromUrl(dbUrl)
    const driver = createPostgresDriver(profile, endpointFor(profile), { onError: () => {} })
    try {
      expect(await driver.connect()).toMatch(/^PostgreSQL \d+/)
    } finally {
      await driver.disconnect()
    }
  })

  it('returns columns, rows, rowCount and a duration for a select', async () => {
    const driver = await connectDriver()
    try {
      const result = await driver.query('select 1 as a, 2 as b')
      expect(result.columns).toEqual(['a', 'b'])
      expect(result.rows).toEqual([[1, 2]])
      expect(result.rowCount).toBe(1)
      expect(result.truncated).toBe(false)
      expect(result.durationMs).toBeGreaterThanOrEqual(0)
    } finally {
      await driver.disconnect()
    }
  })

  it('binds positional parameters', async () => {
    const driver = await connectDriver()
    try {
      const result = await driver.query('select $1::int as x, $2::text as y', [7, 'hi'])
      expect(result.columns).toEqual(['x', 'y'])
      expect(result.rows).toEqual([[7, 'hi']])
    } finally {
      await driver.disconnect()
    }
  })

  it('runs a write batch atomically: commits all, or rolls back all on failure', async () => {
    const driver = await connectDriver()
    try {
      await driver.query('create table sqlkit_it.batch (id integer primary key, v text)')
      // All statements succeed → both rows commit.
      const ok = await driver.runBatch!([
        { sql: 'insert into sqlkit_it.batch (id, v) values ($1, $2)', params: [1, 'a'] },
        { sql: 'insert into sqlkit_it.batch (id, v) values ($1, $2)', params: [2, 'b'] },
      ])
      expect(ok).toEqual({ success: true })
      expect((await driver.query('select count(*)::int from sqlkit_it.batch')).rows).toEqual([[2]])

      // Second insert violates the primary key → the first must roll back too.
      const bad = await driver.runBatch!([
        { sql: 'insert into sqlkit_it.batch (id, v) values ($1, $2)', params: [3, 'c'] },
        { sql: 'insert into sqlkit_it.batch (id, v) values ($1, $2)', params: [1, 'dup'] },
      ])
      expect(bad.success).toBe(false)
      if (!bad.success) expect(bad.failedIndex).toBe(1)
      expect((await driver.query('select count(*)::int from sqlkit_it.batch')).rows).toEqual([[2]])
    } finally {
      await driver.query('drop table if exists sqlkit_it.batch').catch(() => {})
      await driver.disconnect()
    }
  })

  it('surfaces SQL errors', async () => {
    const driver = await connectDriver()
    try {
      await expect(driver.query('select * from sqlkit_no_such_table')).rejects.toThrow(/sqlkit_no_such_table|does not exist/i)
    } finally {
      await driver.disconnect()
    }
  })

  it('executes a SQL-standard BEGIN ATOMIC function body as one statement', async () => {
    const driver = await connectDriver()
    try {
      await driver.query(`create or replace function sqlkit_it.atomic_one() returns integer language sql
        begin atomic
          select 1;
        end`)
      expect((await driver.query('select sqlkit_it.atomic_one()')).rows).toEqual([[1]])
    } finally {
      await driver.disconnect()
    }
  })

  it('drains a capped read without cancelling statement semantics', async () => {
    const driver = await connectDriver()
    try {
      const count = MAX_BUFFERED_ROWS + 25
      const result = await driver.query('select generate_series(1, $1) as n', [count])
      expect(result.rows).toHaveLength(MAX_BUFFERED_ROWS)
      expect(result.rowCount).toBe(count)
      expect(result.truncated).toBe(true)
      expect(result.rowCountExact).toBe(true)
    } finally {
      await driver.disconnect()
    }
  }, 20000)

  it('does not leak session state between pooled query runs', async () => {
    const driver = await connectDriver()
    try {
      await driver.query("set application_name = 'sqlkit-leaked-state'")
      expect((await driver.query("select current_setting('application_name')")).rows[0]?.[0]).not.toBe('sqlkit-leaked-state')
    } finally {
      await driver.disconnect()
    }
  })

  it('re-resolves cached column sources after DDL changes the catalog', async () => {
    const driver = await connectDriver()
    try {
      await driver.query('drop table if exists src_probe; create table src_probe (a int)')
      const before = await driver.query('select * from src_probe')
      expect(before.columnSources?.[0]?.column).toBe('a')
      // Same query again — served from the cache, must still be right.
      expect((await driver.query('select * from src_probe')).columnSources?.[0]?.column).toBe('a')
      // The rename keeps the column's (attrelid, attnum) key, so a stale cache
      // would keep reporting 'a' — which the grid write path would target.
      await driver.query('alter table src_probe rename column a to b')
      expect((await driver.query('select * from src_probe')).columnSources?.[0]?.column).toBe('b')
    } finally {
      await driver.query('drop table if exists src_probe').catch(() => {})
      await driver.disconnect()
    }
  })

  it('preserves temporal and exact numeric values as text', async () => {
    const driver = await connectDriver()
    try {
      const result = await driver.query(
        "select date '2026-07-10', timestamp '2026-07-10 03:04:05.123456', timestamptz '2026-07-10 03:04:05.123456+08', 12345678901234567890.1234::numeric",
      )
      expect(result.rows[0]).toEqual([
        '2026-07-10',
        '2026-07-10 03:04:05.123456',
        '2026-07-09 19:04:05.123456+00',
        '12345678901234567890.1234',
      ])
      const arrays = await driver.query("select array[12345678901234567890.1234::numeric, 2]")
      expect(arrays.rows[0]).toEqual(['{12345678901234567890.1234,2}'])
    } finally {
      await driver.disconnect()
    }
  })

  it('reports the schema/table/column source of each result column', async () => {
    const driver = await connectDriver()
    try {
      const result = await driver.query('select id, name, 1 as lit from sqlkit_it.authors order by id limit 1')
      expect(result.columnSources?.[0]).toEqual({ schema: 'sqlkit_it', table: 'authors', column: 'id' })
      expect(result.columnSources?.[1]).toEqual({ schema: 'sqlkit_it', table: 'authors', column: 'name' })
      expect(result.columnSources?.[2]).toEqual({ schema: null, table: null, column: null })
    } finally {
      await driver.disconnect()
    }
  })

  it('keeps rows aligned with each result set in a multi-statement run', async () => {
    const driver = await connectDriver()
    try {
      const result = await driver.query('select 1 as a; select 2 as b')
      expect(result.columns).toEqual(['b'])
      expect(result.rows).toEqual([[2]])
      expect(result.resultSets?.map((set) => ({ columns: set.columns, rows: set.rows }))).toEqual([
        { columns: ['a'], rows: [[1]] },
        { columns: ['b'], rows: [[2]] },
      ])
    } finally {
      await driver.disconnect()
    }
  })

  it('cancels an in-flight query from an out-of-band connection', async () => {
    const driver = await connectDriver()
    try {
      const running = driver.query('select pg_sleep(30)', [], null, null, null, 'slow-query')
      // Attach the rejection expectation before cancelling so the reject has a
      // handler the instant it fires (no transient unhandled rejection).
      const cancelled = expect(running).rejects.toThrow('Query cancelled.')
      await new Promise((resolve) => setTimeout(resolve, 400))
      expect(await driver.cancel?.('other-query')).toEqual({ running: 0, cancelled: 0 })
      const outcome = await driver.cancel?.('slow-query')
      expect(outcome?.running).toBeGreaterThanOrEqual(1)
      expect(outcome?.cancelled).toBeGreaterThanOrEqual(1)
      await cancelled
      expect((await driver.query('select 1')).rows).toEqual([[1]])
    } finally {
      await driver.disconnect()
    }
  }, 20000)

  it('cancels an in-flight streaming export', async () => {
    const driver = await connectDriver()
    const file = exportFile('slow.csv')
    try {
      const running = driver.exportQuery!({
        sql: 'select pg_sleep(30) as x',
        params: [],
        childDb: null,
        sort: null,
        filePath: file,
        format: 'csv',
        executionId: 'slow-export',
      })
      const cancelled = expect(running).rejects.toThrow('Query cancelled.')
      await new Promise((resolve) => setTimeout(resolve, 400))
      const outcome = await driver.cancel?.('slow-export')
      expect(outcome?.running).toBeGreaterThanOrEqual(1)
      expect(outcome?.cancelled).toBeGreaterThanOrEqual(1)
      await cancelled
      expect((await driver.query('select 1')).rows).toEqual([[1]])
    } finally {
      await driver.disconnect()
    }
  }, 20000)

  it('reports nothing running when cancel finds no in-flight query', async () => {
    const driver = await connectDriver()
    try {
      expect(await driver.cancel?.()).toEqual({ running: 0, cancelled: 0 })
    } finally {
      await driver.disconnect()
    }
  })

  it('lists tables, views and matviews with their schema', async () => {
    const driver = await connectDriver()
    try {
      const mine = (await driver.listTables()).filter((table) => table.schema === 'sqlkit_it')
      expect(mine).toEqual(
        expect.arrayContaining([
          { schema: 'sqlkit_it', name: 'authors', kind: 'table' },
          { schema: 'sqlkit_it', name: 'books', kind: 'table' },
          { schema: 'sqlkit_it', name: 'book_titles', kind: 'view' },
        ]),
      )
    } finally {
      await driver.disconnect()
    }
  })

  it('reports column type, nullability and key flags', async () => {
    const driver = await connectDriver()
    try {
      const columns = await driver.listColumns()
      const find = (table: string, name: string) =>
        columns.find((column) => column.schema === 'sqlkit_it' && column.table === table && column.name === name)
      expect(find('authors', 'id')).toMatchObject({ primaryKey: true, nullable: false })
      expect(find('authors', 'bio')).toMatchObject({ nullable: true, primaryKey: false, foreignKey: false })
      expect(find('books', 'author_id')).toMatchObject({ foreignKey: true, nullable: false })
    } finally {
      await driver.disconnect()
    }
  })

  it('resolves the foreign-key target so a result cell can be followed', async () => {
    const driver = await connectDriver()
    try {
      const columns = await driver.listColumns()
      const find = (table: string, name: string) =>
        columns.find((column) => column.schema === 'sqlkit_it' && column.table === table && column.name === name)
      expect(find('books', 'author_id')?.references).toEqual({
        schema: 'sqlkit_it',
        table: 'authors',
        column: 'id',
        constraint: expect.any(String),
      })
      // A plain column gains no target, so a caller can't navigate from one.
      expect(find('books', 'title')?.references).toBeUndefined()
    } finally {
      await driver.disconnect()
    }
  })

  it('pairs a composite foreign key positionally and groups it under one constraint', async () => {
    await admin.query('drop table if exists sqlkit_it.fk_child, sqlkit_it.fk_parent cascade')
    await admin.query('create table sqlkit_it.fk_parent (a int, b int, primary key (a, b))')
    await admin.query(
      `create table sqlkit_it.fk_child (id serial primary key, pa int, pb int,
         constraint fk_child_comp foreign key (pa, pb) references sqlkit_it.fk_parent(a, b))`,
    )
    const driver = await connectDriver()
    try {
      const columns = await driver.listColumns()
      const find = (name: string) =>
        columns.find((column) => column.schema === 'sqlkit_it' && column.table === 'fk_child' && column.name === name)
      // conkey and confkey are positionally paired: pa must land on a, pb on b.
      expect(find('pa')?.references).toMatchObject({ table: 'fk_parent', column: 'a', constraint: 'fk_child_comp' })
      expect(find('pb')?.references).toMatchObject({ table: 'fk_parent', column: 'b', constraint: 'fk_child_comp' })
      // Sharing a constraint is what lets a caller recognise a composite key and
      // refuse to navigate half of it.
      expect(find('pa')?.references?.constraint).toBe(find('pb')?.references?.constraint)
    } finally {
      await driver.disconnect()
      await admin.query('drop table if exists sqlkit_it.fk_child, sqlkit_it.fk_parent cascade')
    }
  })

  it('lists user-defined types via listObjects', async () => {
    const driver = await connectDriver()
    try {
      const objects = await driver.listObjects?.()
      expect(objects?.types).toEqual(expect.arrayContaining([{ schema: 'sqlkit_it', name: 'mood', detail: 'enum' }]))
    } finally {
      await driver.disconnect()
    }
  })

  it('inspects a table: columns, foreign keys and indexes', async () => {
    const driver = await connectDriver()
    try {
      const inspection = await driver.inspectTable({ schema: 'sqlkit_it', name: 'books', kind: 'table' })
      expect(inspection.columns.map((column) => column.name)).toEqual(['id', 'author_id', 'title', 'published'])
      expect(inspection.columns[0]).toMatchObject({ identity: 'default' })
      expect(inspection.columns.find((column) => column.name === 'author_id')).toMatchObject({ foreignKey: true })
      const foreignKeys = inspection.sections.find((section) => section.title === 'Foreign Keys')
      expect(foreignKeys?.rows[0]?.definition).toMatch(/REFERENCES sqlkit_it\.authors/i)
      const indexes = inspection.sections.find((section) => section.title === 'Indexes')
      expect(indexes?.rows.some((row) => row.name === 'books_author_idx')).toBe(true)
      const constraints = inspection.sections.find((section) => section.title === 'Constraints')
      expect(constraints?.rows.some((row) => /^PRIMARY KEY \(id\)/i.test(row.definition))).toBe(true)
    } finally {
      await driver.disconnect()
    }
  })

  it('executes generated schema-object DDL and exposes it through inspection', async () => {
    const driver = await connectDriver()
    const source = { schema: 'sqlkit_it', name: 'ddl_source', kind: 'table' as const }
    try {
      await driver.query('create table sqlkit_it.ddl_target (id integer primary key)')
      await driver.query('create table sqlkit_it.ddl_source (id integer, target_id integer)')
      await driver.query('create function sqlkit_it.ddl_touch() returns trigger language plpgsql as $$ begin return new; end $$')
      const result = await driver.runDdl!([
        buildCreateIndex(source, { name: 'ddl_source_idx', columns: ['target_id'], unique: false }, 'postgresql'),
        buildAddConstraint(source, { name: 'ddl_source_check', type: 'CHECK', expression: 'id >= 0' }, 'postgresql'),
        buildAddForeignKey(source, {
          name: 'ddl_source_fk', columns: ['target_id'], refTable: 'sqlkit_it.ddl_target', refColumns: ['id'],
        }, 'postgresql'),
        buildCreateTrigger(source, {
          name: 'ddl_source_trigger', timing: 'BEFORE', events: ['INSERT'], level: 'ROW', functionName: 'sqlkit_it.ddl_touch',
        }, 'postgresql'),
      ])
      expect(result).toEqual({ success: true })
      const inspection = await driver.inspectTable(source)
      expect(inspection.sections.find((section) => section.title === 'Indexes')?.rows.some((row) => row.name === 'ddl_source_idx')).toBe(true)
      expect(inspection.sections.find((section) => section.title === 'Foreign Keys')?.rows.some((row) => row.name === 'ddl_source_fk')).toBe(true)
      expect(inspection.sections.find((section) => section.title === 'Triggers')?.rows.some((row) => row.name === 'ddl_source_trigger')).toBe(true)

      await driver.query('create table sqlkit_it.ddl_partitioned (id integer) partition by range (id)')
      expect(await driver.runDdl!([
        buildAddPartition({ schema: 'sqlkit_it', name: 'ddl_partitioned', kind: 'table' }, { name: 'ddl_partition_10', bounds: 'FROM (0) TO (10)' }, 'postgresql'),
      ])).toEqual({ success: true })
    } finally {
      await driver.query('drop table if exists sqlkit_it.ddl_partitioned cascade').catch(() => {})
      await driver.query('drop table if exists sqlkit_it.ddl_source cascade').catch(() => {})
      await driver.query('drop table if exists sqlkit_it.ddl_target cascade').catch(() => {})
      await driver.query('drop function if exists sqlkit_it.ddl_touch() cascade').catch(() => {})
      await driver.disconnect()
    }
  })

  it('inspects an enum type: its values in order', async () => {
    const driver = await connectDriver()
    try {
      const inspection = await driver.inspectObject?.({ schema: 'sqlkit_it', name: 'mood', detail: 'enum' }, 'type')
      const values = inspection?.sections.find((section) => section.title === 'Values')
      expect(values?.rows.map((row) => row.name)).toEqual(['happy', 'sad'])
    } finally {
      await driver.disconnect()
    }
  })

  it('creates and drops a database', async () => {
    const driver = await connectDriver()
    const name = 'sqlkit_it_created'
    try {
      await admin.query(`drop database if exists ${name}`)
      await driver.createDatabase?.(name)
      expect((await admin.query('select 1 from pg_database where datname = $1', [name])).rowCount).toBe(1)
      await driver.dropDatabase?.(name)
      expect((await admin.query('select 1 from pg_database where datname = $1', [name])).rowCount).toBe(0)
    } finally {
      await admin.query(`drop database if exists ${name}`).catch(() => {})
      await driver.disconnect()
    }
  })

  it('refuses to drop the database currently in use', async () => {
    const driver = await connectDriver()
    try {
      const active = profileFromUrl(dbUrl).database
      await expect(driver.dropDatabase?.(active)).rejects.toThrow(/currently in use/i)
    } finally {
      await driver.disconnect()
    }
  })

  it('lists and switches child databases in all-databases mode', async () => {
    const driver = await connectDriver({ databaseMode: 'all' })
    try {
      const children = driver.children?.() ?? []
      expect(children.length).toBeGreaterThan(0)
      const active = profileFromUrl(dbUrl).database
      expect(children.find((child) => child.name === active)?.inUse).toBe(true)
      const other = children.find((child) => child.name !== active)
      if (other) {
        expect(driver.useChild?.(other.name)).toBe(true)
        expect(driver.children?.().find((child) => child.name === other.name)?.inUse).toBe(true)
      }
      expect(driver.useChild?.('sqlkit_no_such_database')).toBe(false)
    } finally {
      await driver.disconnect()
    }
  })

  // Verifies the serverActivity SQL against the real catalogs — the shapes it
  // reads (bigint-as-text elapsed, unlimited connection caps, non-client
  // threads) differ enough per engine to be worth pinning.
  it('reports connection usage, uptime and its own session', async () => {
    const driver = await connectDriver()
    // A second connection from the app, so there is a self session to find: the
    // reader excludes itself from the list it produces.
    const other = await connectDriver()
    try {
      const activity = await driver.serverActivity!()
      expect(activity.selfIdentificationAvailable).toBe(true)
      expect(activity.sessions.some((session) => session.self)).toBe(true)

      expect(activity.connections.used).toBeGreaterThan(0)
      expect(activity.connections.max === null || activity.connections.max > 0).toBe(true)
      expect(activity.stats.some((stat) => stat.label === 'Uptime' && stat.value !== '')).toBe(true)

      for (const session of activity.sessions) {
        expect(typeof session.id).toBe('string')
        expect(session.id).not.toBe('')
        // elapsedMs must be a real number, never a bigint string.
        expect(session.elapsedMs === null || Number.isFinite(session.elapsedMs)).toBe(true)
        expect(typeof session.self).toBe('boolean')
      }
    } finally {
      await other.disconnect()
      await driver.disconnect()
    }
  })

  it('rejects an unusable session id rather than building bad SQL', async () => {
    const driver = await connectDriver()
    try {
      await expect(driver.endSession!('7; drop table x', 'terminate')).rejects.toThrow()
    } finally {
      await driver.disconnect()
    }
  })

})

// A transaction-pooling proxy in front of the same server. It hands each client
// a synthetic BackendKeyData, so pg_cancel_backend against that PID returns
// false and the statement runs to completion — cancellation only lands over the
// wire protocol. Verified against PgBouncer 1.25.2 in transaction mode; skipped
// unless TEST_POOLED_DATABASE_URL points at one.
const pooledUrl = testPooledDatabaseUrl()
const describePooled = pooledUrl ? describe : describe.skip

describePooled('postgres driver through a transaction pooler (integration)', () => {
  const connectPooled = async (): Promise<Driver> => {
    const profile = profileFromUrl(pooledUrl!, { databaseMode: 'single' })
    const driver = createPostgresDriver(profile, endpointFor(profile), { onError: () => {} })
    await driver.connect()
    return driver
  }

  it('cancels an in-flight query over the wire protocol', async () => {
    const driver = await connectPooled()
    try {
      const running = driver.query('select pg_sleep(20)', [], null, null, null, 'slow-pooled')
      const cancelled = expect(running).rejects.toThrow('Query cancelled.')
      await new Promise((resolve) => setTimeout(resolve, 400))
      const started = Date.now()
      const outcome = await driver.cancel?.('slow-pooled')
      expect(outcome?.running).toBeGreaterThanOrEqual(1)
      expect(outcome?.cancelled).toBeGreaterThanOrEqual(1)
      await cancelled
      // The point of the test: interrupted promptly, not after pg_sleep(20).
      expect(Date.now() - started).toBeLessThan(5_000)
      expect((await driver.query('select 1')).rows).toEqual([[1]])
    } finally {
      await driver.disconnect()
    }
  }, 30_000)

  it('resets a pooled session between queries', async () => {
    // DISCARD ALL is passed through by PgBouncer rather than refused, so the
    // ordinary reset path works here too; this pins that behavior so a pooler
    // that does refuse it shows up as a failure rather than silent churn.
    const driver = await connectPooled()
    try {
      await driver.query("set search_path to pg_catalog")
      expect((await driver.query('show search_path')).rows[0]?.[0]).not.toBe('pg_catalog')
    } finally {
      await driver.disconnect()
    }
  })
})
